import unittest
import pytest

from unittest.mock import patch, mock_open
from advent_of_code_2025_python.days.day7.Day7 import Day7

class TestDay6:

    @pytest.fixture()
    def day7_instance(self):
        return Day7("")

    def test_run_1(self, day7_instance):
        mock_data = """.......S.......
...............
.......^.......
...............
......^.^......
...............
.....^.^.^.....
...............
....^.^...^....
...............
...^.^...^.^...
...............
..^...^.....^..
...............
.^.^.^.^.^...^.
..............."""

        with patch("builtins.open", mock_open(read_data=mock_data)):
            result = day7_instance.run()
        assert result == "21"

    def test_run_2(self, day7_instance):
        mock_data = """.......S.......
...............
.......^.......
...............
......^.^......
...............
.....^.^.^.....
...............
....^.^...^....
...............
...^.^...^.^...
...............
..^...^.....^..
...............
.^.^.^.^.^...^.
..............."""

        with patch("builtins.open", mock_open(read_data=mock_data)):
            result = day7_instance.run2()
        assert result == "40"

if __name__ == "__main__":
    unittest.main()
